cc_binary(
    name = "custom_traffic_lights",
    srcs = ["custom_traffic_lights.cc"],
    deps = [
        "//cyber",
        "//modules/perception/proto:traffic_light_detection_cc_proto",
        "//modules/common/proto:header_cc_proto",
        "//modules/common/proto:error_code_cc_proto",
    ],
)
