cc_binary(
    name = "custom_obstacles",
    srcs = ["custom_obstacles.cc"],
    deps = [
        "//cyber",
        "//modules/perception/proto:perception_obstacle_cc_proto",
        "//modules/map/proto:map_lane_cc_proto",
        "//modules/map/proto:map_id_cc_proto",
        "//modules/map/proto:map_geometry_cc_proto",
    ],
)
